### ISSUE TITLE
Volume list error: template: OutputYamlTpl:24:74

### ISSUE THREAD

**Issue by davidq2q** [openebs/maya#1050]
Issue same as: https://github.com/openebs/maya/issues/870 on 0.8.1 release.
That issue was already closed but it still occurs on latest version.

mayactl version
```Version: 0.8.1-released
Git commit: 43ad5ca8f3d36995afbce3914d0be8ecd8a8de13
GO Version: go1.11.2
GO ARCH: amd64
GO OS: linux
m-apiserver url:  http://10.233.66.175:5656
m-apiserver status:  running
```

**Comment by kmova** [comment]
We have with 2.x releases and CSI driver based provisioning, moved away from cas templates. The new provisioners are available at: 

https://github.com/openebs/cstor-operators
https://github.com/openebs/jiva-operator
