### ISSUE TITLE
Provision the networking scheme for the VSM

### ISSUE THREAD

**Issue by kmova** [openebs/maya#11]
Since the replica's and controllers may need to communicate beyond the boundaries of a docker cluster, we will be using "host" based networking scheme. Before a VSM is scheduled, it should be allocated with an IP address for exposing the iSCSI volumes and a set of replica IP/Address and ports.

**Comment by AmitKumarDas** [comment]
Do the compute layer (*i.e. client to iscsi volumes*) require all these IPs ?
What is the need to provide IP addresses for replicas ?
What is the need to provide the ports for replicas ?
What is the need to provide port addresses for controller ?

**Comment by AmitKumarDas** [comment]
Working out below features:

```
mayactl network-create
mayactl network-rm
mayactl network-list
```

Will be referring to: https://github.com/containernetworking/cni/ & its plugin for the first cut version !!

**Comment by kmova** [comment]
For milestone 0.1, static ip are used using a wrapper around docker launch.
