### ISSUE TITLE
Un-required error messages in mayactl

### ISSUE THREAD

**Issue by shubham14bajpai** [openebs/maya#1129]
**What is the current error reporting**
Right now we have error messages with large objects and extra details being displayed in case of an error.

![Screenshot from 2019-05-02 16-29-08](https://user-images.githubusercontent.com/16064787/57072115-2f23a600-6cfa-11e9-8794-dc9b43624de7.png)

**What is required**
We require small information regarding failure by default
```
user:my$ mayactl -m 10.99.138.134 volume list
Volume list error: failed to list volumes
```
 and the objects and other details by using ``--verbose``

**Comment by AmitKumarDas** [comment]
@shubham14bajpai the default error message should be `failed to list volumes`
