### ISSUE TITLE
refactor Provisioner.createCleanupPod(cmdsForPath []string, name, path, node string)

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/maya#1162]
I've selected [**Provisioner.createCleanupPod(cmdsForPath []string, name, path, node string)**](https://github.com/openebs/maya/blob/bb7e32b2a93b16c2654eda2301308bd379679799/cmd/provisioner-localpv/app/helper.go#L87-L165) for refactoring, which is a unit of **62** lines of code. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Short Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the length of code units to 15 lines of code.
- **Why**❓ 
Small units are easier to analyse, test and reuse.
- **How** 🔧 
When writing new units, don't let them grow above 15 lines of code. When a unit grows beyond this, split it in smaller units of no longer than 15 lines.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by agarwalrounak** [comment]
I will take this up.
