### ISSUE TITLE
BDD test to create and delete local PV

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/maya#1192]
### What this issue is about?
This issue caters to implementation of BDD tests _(using ginkgo)_ to verify successful creation and subsequent deletion of local persistent volume.

### References
- https://github.com/openebs/maya/commit/49f63f75a70de6b38769024cb6a0bc6a5915518c
- https://github.com/openebs/maya/commit/b8674d44f29b67aea12b4f3d20a7b15323662591

### Mentors
- @AmitKumarDas

**Comment by rampreeth** [comment]
@AmitKumarDas  can I pick this up?

**Comment by AmitKumarDas** [comment]
Yes. You can
