### ISSUE TITLE
BDD test for jiva volume provisioning in openebs namespace 

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/maya#1193]
FEATURE REQUEST

Implement BDD test using ginkgo and gomega which will provision jiva volume in openebs namespace.
Steps:
1. Create volume ,write some data 
2. Create snapshot and 
3. Create a clone volume using the snapshot 
4. Delete the source volume and clone volume.

Refer https://github.com/openebs/maya/pull/1183 for more details about related to StorageClass changes.

**Comment by shubham14bajpai** [comment]
This test is no longer valid as jiva now creates resources only in openebs namespace.
