### ISSUE TITLE
Local PV support for ReadWriteMany

### ISSUE THREAD

**Issue by danishsamad** [openebs/maya#1342]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

**What happened**:
In trying to provision a pod with a PVC using local PV and accessmode set to ReadWriteMany, PVC binding fails with following exception; "failed to provision volume with StorageClass “openebs-hostpath-custom”: Only support ReadWriteOnce access mode”

**What you expected to happen**:
The local PV feature should support the RWX feature and in case multiple pods are requesting the same PVC all of them should be scheduled to same node as the PV.

**How to reproduce it (as minimally and precisely as possible)**:
**storageclass.yaml:**
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-hostpath-custom
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: BasePath
        value: "/mnt/"
provisioner: openebs.io/local
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

**PVC_POD.yaml**
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-pv-claim
spec:
  storageClassName: openebs-hostpath-custom
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: ubuntu
spec:
  restartPolicy: Always
  containers:
    - name: ubuntu
      image: ubuntu:latest
       # Just spin & wait forever
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
      - mountPath: "/mnt/azure"
        name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: openebs-pv-claim

**Anything else we need to know?**:

**Environment**:
AKS Cluster (3 noedes) using K8s version 1.14 with each node having an ephemeral storage of 200 GB.
openebs version 1.0
Installation instructions followed from this [link ](https://docs.openebs.io/docs/next/installation.html)
Local PV setup using hostpath option as described [here ](https://docs.openebs.io/docs/next/uglocalpv.html#Provision-OpenEBS-Local-PV-based-on-hostpath)

**Comment by pre** [comment]
Related https://github.com/openebs/openebs/issues/3132

**Comment by kenotsolutions** [comment]
workaround for this issue use StatefulSet instead of Deployment. Use volumeClaimTemplates for the StatefulSet so it would create a PVC for each node.

**Comment by pre** [comment]
> workaround for this issue use StatefulSet instead of Deployment.

This is a solution to another problem, not a workaround for this issue. Further comments in 
https://github.com/openebs/openebs/issues/3132#issuecomment-700489753

**Comment by WojoInc** [comment]
Stumbled across this, is there a reason that LocalPV would need to support RWX? RWX refers to ReadWriteMany across nodes. It should not be required in single node setups or in cases like LocalPV where the volume and the pod would reside on the same node. RWO should cover multiple pods accessing the same volume read-write on the same node.

**Comment by kmova** [comment]
Indeed Local PV can be used for access to get access to multiple pods on the same node. 

@danishsamad did you get to test this out?

**Comment by danishsamad** [comment]
> Indeed Local PV can be used for access to get access to multiple pods on the same node.
> 
> @danishsamad did you get to test this out?

No. This was a long time ago and I don't recall our use case but we decided to use an alternate (non-openebs) approach

**Comment by madalinignisca** [comment]
@WojoInc RWO will not allow using same volume between multiple different pods or replicas even in the same node. Having localpv able to do RWX allows testing cases like scalability of apps before preprod and prod deployments.

**Comment by kro-cat** [comment]
I'd like to add my support to this feature request instead of opening up a new one. RWX is a required localPV mode when GFS2 is being used by nodes. I'd like to see this implemented in OpenEBS, but I'll probably move on to using a different method for dynamic creation of localpvs
