### ISSUE TITLE
refactor cstorcompletedbackup and cstorbackup spec

### ISSUE THREAD

**Issue by mynktl** [openebs/maya#1653]
As of now CStorCompletedBackup and CStorBackups are using the same [spec](https://github.com/openebs/maya/blob/master/pkg/apis/openebs.io/v1alpha1/cstor_backup.go#L37) to store backup related information. 

This issue is to create a new spec for CStorCompletedBackup with following details.

- LastSnapName
- SecondLastSnapName

_Originally posted by @kmova in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjUwNjUwOTY0OnYy/pull_request_review_threads/discussion_

**Comment by mynktl** [comment]
update:
- etcd version of cstocompletedbackup also needs to get updated. To support that upgrade jobs needs to be added for updating etcd version and CRD.

**Comment by mittachaitu** [comment]
https://docs.google.com/document/d/1kwCCYCFrcc51A7Xdt9fHmXOk32Z3J1FJQJyMPld9QbI/edit?usp=sharing
The approach document was rolled out waiting for polishing and reviews
