### ISSUE TITLE
zpool and zfs command execution using CSP

### ISSUE THREAD

**Issue by mittachaitu** [openebs/maya#1746]
**Describe the problem/challenge you have**
High-level operators should be able to perform 
zpool/zfs get zpool/zfs command execution to
use the output for their services.

**Describe the solution you'd like**
CSP can have a separate field to take command as an input.
After finding command on field pool-mgmt controller should execute
the command and set the output on the status if it succeeds. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- OpenEBS version
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by mittachaitu** [comment]
https://github.com/openebs/openebs/pull/3116 OEP has been raised to address the issue.

**Comment by shubham14bajpai** [comment]
This was required for migrating the SPC to CSPC. Another approach was followed where pod/exec worked fine.
