### ISSUE TITLE
"admission-webhook.openebs.io" does not support dry run

### ISSUE THREAD

**Issue by mpartel** [openebs/maya#1771]
## Description
When running `kubectl diff` or `kubectl apply --dry-run` on a config that defines a `PersistentVolumeClaim`, I get this error:
`admission webhook "admission-webhook.openebs.io" does not support dry run`

## Possible Solution
You can mark the [ValidatingWebhook](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#validatingwebhook-v1beta1-admissionregistration-k8s-io) resource that OpenEBS installs in [`webhook/configuration.go`](https://github.com/openebs/maya/blob/1bc54a4501cc3277c4928b503d66646ac2857273/pkg/webhook/configuration.go#L200) as `sideEffects: None` or `NoneOnDryRun`, assuming the webhook indeed has no side-effects.

I can make a PR if that helps, but I'd prefer if a dev could tell me whether the webhook has no side-effects rather than reading through all that the code myself.

**Comment by mpartel** [comment]
Workaround: since maya doesn't overwrite the config if it exists, and since it *appears* there are no side-effects, it seems safe to modify the config after it appears.

**Comment by prateekpandey14** [comment]
@mpartel i have tried to run the --dry-run command, but not gettting any error, can you share the k8s version you are trying ?

```
$ kubectl apply --dry-run -f cstor-pvc.yaml
persistentvolumeclaim/cstor-test created (dry run)
```

**Comment by mpartel** [comment]
It was either 1.19.3 or 1.19.4

**Comment by prateekpandey14** [comment]
Ok , i think you already tried by setting the `SideEffects: None` and it should work fine. I am going to raise a PR with that change anyways. thanks

**Comment by mpartel** [comment]
Yeah, I've seen no problems having set that manually :+1:
Thanks!
