### ISSUE TITLE
New maya cli - Require a command to drain the node from maya cluster

### ISSUE THREAD

**Issue by umamukkara** [openebs/maya#30]
Currently we have a command to add the node to the cluster

```bash
$ maya setup-osh -omm-ips -self-ip
```

There needs to be a command to drain the node from the cluster

```bash
$ maya drain-osh <host-id>
```

**Comment by ashishranjan738** [comment]
@umamukkara  I would like to work on this issue.

**Comment by ashishranjan738** [comment]
Can i get some more information regarding this .
