### ISSUE TITLE
missing period and hyphens in README file

### ISSUE THREAD

**Issue by sachinmukherjee** [openebs/maya#324]
BUG REPORT 

**What happened**:
- Missing periods at the end of a sentence in README.md file.
- Missing hyphens between *api* and *server*. Current scenario it is written like this `maya-apiserver` but it should be like this `maya-api-server` in README.md file.

**What you expected to happen**:

Add missing period and hyphen at appropriate places.

**Comment by utkarsh2102** [comment]
Hi,
I'd like to take up this issue.
Please assign the same to me.

**Comment by utkarsh2102** [comment]
@kmova, please review #341 in reference to this issue.
