### ISSUE TITLE
maya osh-status gets error at the querying node ..

### ISSUE THREAD

**Issue by sripadaraj** [openebs/maya#39]
error querying node status

**Comment by maheshreddy7797** [comment]
![osh_status](https://cloud.githubusercontent.com/assets/17985380/23935986/65927f30-0975-11e7-96f3-a1f03edd19ec.png)

**Comment by prateekpandey14** [comment]
Run this command `source ~/.profile`

**Comment by maheshreddy7797** [comment]
yep!! we did that previously, but throws same error.

**Comment by maheshreddy7797** [comment]
Later i restarted all VM's then it works fine.

**Comment by sripadaraj** [comment]
Yes but error is seen ....

**Comment by sripadaraj** [comment]
got fixed the issue
