### ISSUE TITLE
Openebs fails to setup in maya host-02

### ISSUE THREAD

**Issue by maheshreddy7797** [openebs/maya#40]
![host02_osh_failure](https://cloud.githubusercontent.com/assets/17985380/23936901/9b2bcd18-097a-11e7-8c4f-fbb3f11392f5.png)
@AmitKumarDas @prateekpandey14 @kmova ##39

**Comment by sripadaraj** [comment]
It fails in both host-1 and host-2

**Comment by maheshreddy7797** [comment]
fixed the issue after restarting maya and then host-02 IP is set to 178.28.128.5
