### ISSUE TITLE
wrong number of args for replace: want 3 got 2

### ISSUE THREAD

**Issue by PeterGrace** [openebs/maya#518]
## Is this a BUG REPORT or FEATURE REQUEST?
 BUG REPORT

**What happened**: When executing mayactl volume list, received `Volume list error: template: OutputYamlTpl:24:59: executing "OutputYamlTpl" at <replace>: wrong number of args for replace: want 3 got 2`

**What you expected to happen**: Receive a volume list

**How to reproduce it (as minimally and precisely as possible)**:
  - connect to maya-api-server container in kubernetes
  - execute `mayactl volume list`

**Environment**:
- Maya version (use `maya version`): Version: 0.7.0-unreleased
- M-apiserver version (use `m-apiserver version`):Version: 0.7.0-unreleased/Git commit: 13a810528234e40c8121705e2957dc8d5dfe9519
- OS (e.g. from /etc/os-release): Alpine linux (openebs 0.7.0 provided container)
- Kernel (e.g. `uname -a`): Linux maya-apiserver-69f9cb4c66-gcg8x 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 Linux

- Install tools: OpenEBS 0.7.0 operator pattern
- Others:

**Comment by princerachit** [comment]
This issue has been fixed in subsequent commits. Please make issues in openebs/openebs all issues of maya are tracked there.
