### ISSUE TITLE
Refactor maya and make maya more like a Kit Project

### ISSUE THREAD

**Issue by satyamz** [openebs/maya#62]
I think, we should refactor maya to make it a Kit project which will be useful/common across all the OpenEBS projects. Kit project as explained https://www.goinggo.net/2017/02/package-oriented-design.html

Use case: We need orchprovider at several places such as mayaserver etc. So we can move orchprovider 
inside maya. 
@prateekpandey14, @AmitKumarDas  and @kmova any thoughts?

**Comment by satyamz** [comment]
Also, moving ` *.go ` & other files currently present under `maya/`  into a specific directory will be a good idea.

**Comment by AmitKumarDas** [comment]
@satyamz Can you list down the salient points from above link & others here in this issue. We shall try to focus on those selected points.

**Comment by prateekpandey14** [comment]
@satyamz  Sounds cool, We can keep all maya specific *.go files in a separate dir which will doesn't affected by the any new libs pkg we are going to add in coming future.

**Comment by satyamz** [comment]
Following are some key points:

- `maya` should be a standard library across @openebs organization. 
- We can keep common projects like logs, orchprovider etc. inside `maya`
-  Packages inside `maya` should be portable because we're going to import those packages at several places/projects.
-   Quoting from package oriented design by William Kennedy
   > the Kit project is not allowed to have a vendor folder. If any of packages are dependent on 3rd party packages, they must always build against the latest version of those dependences.


@AmitKumarDas   These are broad points which I think, `maya` as a Kit project should follow. However, we need to be more careful about the last point.  :slightly_smiling_face:

**Comment by satyamz** [comment]
@prateekpandey14 yes! That's a good idea.  I will create a different branch and will start this.

**Comment by AmitKumarDas** [comment]
What about the types, versioning, constants, env variables ? Do these belong to maya kit ?

**Comment by satyamz** [comment]
@AmitKumarDas I was looking at `mayaserver/lib/*` I found that we also need to move `lib/api` because these are dependencies on orchprovider and volumeprovisioner

**Comment by AmitKumarDas** [comment]
### Some more comments

#### pkg & its contents

- The other day we were discussing about pkg/ & its contents.
- We said the common code which does not have any bearing with storage domain should go into this.
- In addition, let us try to re-use the features from other projects in this particular area.
  - `e.g. https://github.com/go-kit/kit`
  - e.g. let us not create a logger or http / net util in maya kit

#### versioning

- I guess the common/kit/core storage logic should use typed inputs & outputs.
- These will becomes storage types.
- These should to be versioned. In addition, the business logic passing / using these types should be 
similarly versioned. In short the end-to-end business flow should be sandboxed in its versions. 
- Care should be taken by consuming libraries to be able to use latest maya kit & still use the older versions. This should be good for backward compatibility without going through the pain of upgrade & then a rollback, etc

**Comment by satyamz** [comment]
@AmitKumarDas I agree with you in `pkg & its contents` on the following points: 


> The other day we were discussing about pkg/ & its contents.
We said the common code which does not have any bearing with storage domain should go into this.
In addition, let us try to re-use the features from other projects in this particular area.
e.g. https://github.com/go-kit/kit

However, I am clear about the second point:

> e.g. let us not create a logger or http / net util in maya kit

Why should not we move common libraries such as logger to Maya? We certainly don't want to create another kit project which will contain this common stuff, right?  

On the `versioning` part: 
 I agree with this. We should consider backward compatibility.
