### ISSUE TITLE
Make on linux subsystem for windows

### ISSUE THREAD

**Issue by k1slay** [openebs/maya#625]
BUG REPORT

**What happened**:
Maya failed to build with the make command

`
~/go/src/github.com/openebs/maya$ make
----------------------------
--> mayactl
----------------------------
==> Removing old directory...
==> Building mayactl using go version go1.11.1 linux/amd64...

==> Packaging...
--> linux_386
/home/kislay/go/src/github.com/openebs/maya/buildscripts/mayactl/build.sh: line 102: zip: command not found
`

**How to reproduce it (as minimally and precisely as possible)**:
On Linux subsystem for windows clone the repo and make

**Environment**:
- Maya version (use `maya version`): 0.7.0
- OS : Windows 10
- Kernel : Linux subsystem for windows (4.4.0-17134-Microsoft)

**Comment by kmova** [comment]
The CLI is being replaced with https://github.com/openebs/openebsctl
