### ISSUE TITLE
Display output using go templates

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/maya#67]
vsm displays some outputs in json (i.e, data coming from m-apiserver), by using template we can display output in a decoupled way.
Have a look on this link [Go playground](https://play.golang.org/p/v310RXD6Gv)

**Comment by sachinmukherjee** [comment]
Is this issue open?

**Comment by utkarshmani1997** [comment]
@sachinmukherjee yes this is already implemented. But i guess there are still some pending work. @prateekpandey14 , @AmitKumarDas are there any pending work related to this issue ^^^.
