### ISSUE TITLE
Rename VSM as Volume. 

### ISSUE THREAD

**Issue by kmova** [openebs/maya#69]
OpenEBS Volumes comprise of a set of containers that are together referred to as VSM. However, this name VSM is confusing, when we try to match to the naming convention of the Container Orchestration Layers. 

To match it to an universally understood concept, we will call this as "Volume", the maya-cli needs to change accordingly:
maya vsm-create -> maya volume-create
maya vsm-stats -> maya volume-stats
maya vsm-stop -> maya volume-delete
maya vsm-snapshots -> maya volume-snapshot

**Comment by AmitKumarDas** [comment]
Just to add further, we had thought following names before concluding on `Volume`:
- `Virtual Storage Machine i.e. VSM`
- `Storage Pod`
- `OpenEBS Container i.e. OC`
- `Storage Container i.e. SC`
- `Storage Container i.e. StorC`

Volume will be simple to talk about as it is already well understood.

**Comment by prateekpandey14** [comment]
Renaming of VSM as Volume is done under this commit ... 57d036f619054dcac10d3f4a07527a90af0731b0
So closing this issue.
