### ISSUE TITLE
Install the maya server dependencies via maya cli -- maya install 

### ISSUE THREAD

**Issue by kmova** [openebs/maya#7]
maya server depends on consul and nomad server being installed. User should be able to trigger the installation of the maya dependencies using "maya install". 

- download the required version of the nomad/consul
- configure nomad/consul as primary server or attach to the existing cluster

**Comment by AmitKumarDas** [comment]
Have codified the consul server part using this [link](https://www.digitalocean.com/community/tutorials/how-to-configure-consul-in-a-production-environment-on-ubuntu-14-04)

**Comment by AmitKumarDas** [comment]
nomad server install related codification is done
