### ISSUE TITLE
Can maya the CLI be more operator friendly ?

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/maya#71]
This is the current approach of using `maya cli` by the operator in a K8s environment.

- Operator needs to login to the machine which has `kubectl` installed & configured to point to a K8s cluster
- Operator needs to know the name of `maya api server` pod.
- Operator will then use `kubectl -it exec <maya api server pod name> /bin/bash` to login to the pod terminal
- Operator will start using maya cli i.e.`maya --help`, etc.

Some issues faced:

- maya cli needs to be searched before being able to use. This is cumbersome.
- Running some HA test cases for OpenEBS volumes, evicted maya api server pod.
  - This requires one to wait for a new maya api pod to come up & start all the above procedures again.
  - One loses the vital observations that needs to be made during HA window
- One can not drop in `maya cli` binary in any K8s master node or any cloud VM & just start using it:
  - Couple or more environment variables needs to be setup
  - Eventually, certificates needs to be set up when security is in place
  - `Install management` is probably the reason why `maya cli` is currently embedded inside the maya api server pod. However, let this issue be a trigger on those thought processes as well,

**Comment by AmitKumarDas** [comment]
> why does the CLI not use REST calls, and thus does not matter”where” it is as long as you point it to the right IP. I kinda expected that to be the case actually ___ @gila

**Comment by kmova** [comment]
kubectl can be installed on the client machine, which is not part of the kubernetes cluster. The kubectl requires a .kubeconfig file that provides credentials to access the kubernetes-apiserver to run its commands. 

Similarly mayacli also can be installed on the client machine and provided with the IP address of the maya-api server to run its commands.

**Comment by AmitKumarDas** [comment]
Closing this issue, since `maya cli`  can communicate over `maya api server` via http.
The IP address (i.e. K8s service IP address for `maya api server pod`) can be used for configuration.
