### ISSUE TITLE
Enhance Maya's Volume Snapshot Feature To Delete Specific Snapshot

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/maya#74]
This Command is to delete the previously created snapshot of a volume, which are no-longer needed
and can be deleted by using maya-cli command.

**Comment by dungeonmaster18** [comment]
Hey @prateekpandey14 , I had one question regarding this. After adding this delete command. If I have to test it how can I do that.

**Comment by fgimenezm** [comment]
I was looking for this too.
Every time a replica POD gets deleted/rescheduled OpenEBS creates a new maya snapshot (not a kubectl managed snapshot) and I was looking for a way to cleanup that.
I don't see a "snapshot delete" command in mayactl. Is this feature implemented somewhere else? Or a workaround?
