### ISSUE TITLE
Install openebs node dependencies via maya cli

### ISSUE THREAD

**Issue by kmova** [openebs/maya#8]
Install the requirement components to convert a node into openebs node by installing:
- docker 
- nomad/consul client
- configuration of persistent store
- configuration of vsm network interfaces

The location of the persistent store and vsm-network interfaces are specific a node. (For example a one node can have mellanox drivers and other in the same cluster can have intel nics. Though not an ideal case, but stuff happens, when putting together the available hardware into a common cluster.)

The details should be stored in the consul ( DB ) on a per node basis. 

maya uses host-based networking for exposing storage. The should be an cli option to specify the network(s) that can be assigned for the VSMs. Whether a network can be used for public (accessing the storage) or private (used for replication). The scope of the networking can be vast, but as part of this issue, it would suffice if the user is able to set the network interface of the node and the range to be used.

**Comment by AmitKumarDas** [comment]
Hi @kmova can you provide sample cli that can be an example for:
- configuring persistence store
- configuring vsm network interfaces

Are there any sample scripts/logic that I can refer to for above items ?

**Comment by AmitKumarDas** [comment]
Will target the persistence store & vsm network in other issues.

The first cut version of `maya install-openebs -master-ips=` is done.
