### ISSUE TITLE
Workflow for launching controller and replica

### ISSUE THREAD

**Issue by kmova** [openebs/maya#9]
- Update the launch arguments for replica containers
  * Pass a backing store (default is local directory) 
- After a replica is launched, indicate to controller about the replica addition

**Comment by kmova** [comment]
Check if nomad allows for pre/post hooks for creating dynamic directories before launching the replica containers. Example, the backing store can be created with the unique id assigned to the replica.

**Comment by AmitKumarDas** [comment]
If Nomad does not allow, we might want to look from Consul's perspective. It has quite a few remediation style techniques. 

*NOTE: As of latest Nomad version (0.5.0) Consul template support is built into job specs.*

**Comment by AmitKumarDas** [comment]
*Query : Can the local backing store be under /var/openebs/<vsmname> ?*

**Comment by kmova** [comment]
backing store directory is configured during the installation of the openebs nodes. It should be fetched from the node config.

**Comment by kmova** [comment]
The backing store is passed as an argument to the launcher scripts. 
https://github.com/openebs/maya/blob/master/demo/jobs/demo-vsm1.hcl


--------------------------------------------------------------------------------------------------
		# Define the controller task to run
		task "rep-store1" {
			# Use a docker wrapper to run the task.
			driver = "raw_exec"
			artifact {
				source = "https://raw.githubusercontent.com/openebs/jiva/master/scripts/launch-jiva-rep-with-ip"
			}

			env {
				JIVA_REP_NAME = "${NOMAD_JOB_NAME}-${NOMAD_TASK_NAME}"
				JIVA_REP_VERSION = "openebs/jiva:latest"
				JIVA_CTL_IP = "${NOMAD_META_JIVA_FRONTENDIP}"
				JIVA_REP_VOLNAME = "${NOMAD_META_JIVA_VOLNAME}"
				JIVA_REP_VOLSIZE = "${NOMAD_META_JIVA_VOLSIZE}"
				JIVA_REP_IP = "172.28.128.102"
				JIVA_REP_SUBNET = "24"
				JIVA_REP_IFACE = "enp0s8"
				**JIVA_REP_VOLSTORE = "/tmp/jiva/vsm1/rep1"**
}
